name: Enforce Safe Go-Live Checklist

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify CHECKLIST.md exists
        run: |
          if [ ! -f CHECKLIST.md ]; then
            echo "❌ CHECKLIST.md is missing!"
            exit 1
          fi

      - name: Verify timestamp present
        run: |
          if ! grep -q "^> Last reset:" CHECKLIST.md; then
            echo "❌ Missing timestamp line at top of CHECKLIST.md"
            exit 1
          fi

      - name: Verify CHECKLIST.md was updated in latest commit
        run: |
          if ! git diff --name-only HEAD~1 HEAD | grep -q "^CHECKLIST.md$"; then
            echo "❌ CHECKLIST.md was not updated in the latest commit."
            exit 1
          fi

      - name: Verify all checklist items are checked
        run: |
          if grep -q "\[ \]" CHECKLIST.md; then
            echo "❌ Checklist not complete! Please check all items before merging."
            exit 1
          else
            echo "✅ Checklist complete. Safe to proceed."
          fi
